# name: Build and deploy Azure

# on:
#   push:
#     branches: [main]
# jobs:
#   build_push_image:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v5

#       - name: Build docker image
#         run: make docker/build

#       - name: Tag docker image
#         run: make docker/tag TAG_NAME=stable

#       # - name: Login to with azure-cli for deploying container apps.
#       #   uses: azure/login@v1
#       #   with:
#       #     creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Login to Azure container registry
#         uses: azure/docker-login@v1
#         with:
#           login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#           username: ${{ secrets.REGISTRY_USERNAME }}
#           password: ${{ secrets.REGISTRY_PASSWORD }}

#       - name: Push the Docker image
#         run: make docker/push

on: [push]
name: Build and deploy test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/hello-world:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/hello-world:${{ github.sha }}
